### ISSUE TITLE
Name a dungeon (simplefloor)

### ISSUE THREAD

**Issue by Yzandril** [DRE2N/DungeonsXL#1020]
**The feature you'd like to know more about**

Hi, I have read the wiki showing how to name a dungeon with multiple levels.

But regarding the creation of a single level dungeon I have not seen a procedure.
To be precise, when a player talks in a dungeon I have the prefix of my chat plugin which says the following:
"DXL_GAME_1" or another number depending on the open instances.

I am using Multichat and it is configured to show the name of each world as a prefix to better locate players, but for DXL dungeons I am not getting the desired result.

Is it possible to prefix the personalized name of a dungeon as for multi-level dungeons?

Sorry if this information is present in the wiki but I admit not having found anything.

Thank you.

**Comment by Sataniel98** [comment]
All instance worlds are named "DXL_Game_ID" or "DXL_Edit_ID" instead of the name of the dungeon no matter if they are part of a single or multi floor dungeon. This is by design sothat multiple instances of the same dungeon can be played simultaneously. Most chat plugins should allow for using a different formatting for certain worlds, so that parameter could be limited to static worlds.

**Comment by Yzandril** [comment]
Thank you for your quick reply. My first idea was to differentiate the player in the main world and the others in the different dungeons. But in fact, with the different authorities, I am going to change my way of doing things. Thanks again.
