### ISSUE TITLE
Can I sync invitorys from the hub to my dungeon?

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#1067]
Can I do that?

**Comment by Sataniel98** [comment]
I'd say inventory synchronization between two servers in a network is a separate task for another plugin. I know some users use https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/, but had to modify it since their DXL integration doesn't really work. (You could probably contact them through our Discord and ask them to share their fix, but I really wouldn't advise using MySQL PDB with DXL.)

The only thing I realistically consider adding at some point is that rewards may be given to the player on another server. But that's not scheduled for DXL 0.18 or 0.19.

A workaround for rewards could be to give players permissions instead that give them access to the items on another server (I'm sure there are ways to share permissions between servers). There's no permission reward, but you can give players permissions through command signs or Vanilla command blocks.

**Comment by ghost** [comment]
> I'd say inventory synchronization between two servers in a network is a separate task for another plugin. I know some users use https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/, but had to modify it since their DXL integration doesn't really work. (You could probably contact them through our Discord and ask them to share their fix, but I really wouldn't advise using MySQL PDB with DXL.)
> 
> The only thing I realistically consider adding at some point is that rewards may be given to the player on another server. But that's not scheduled for DXL 0.18 or 0.19.
> 
> A workaround for rewards could be to give players permissions instead that give them access to the items on another server (I'm sure there are ways to share permissions between servers). There's no permission reward, but you can give players permissions through command signs or Vanilla command blocks.

I phrased it wrong, I mean on my hub on the same server with the dungeons. It wipes the plays invitory how do I make it where it shares it

**Comment by Sataniel98** [comment]
In that case: Yes, as explained here: https://github.com/DRE2N/DungeonsXL/wiki/simple-dungeon
