### ISSUE TITLE
Will you create a cauldron version?

### ISSUE THREAD

**Issue by lord44210** [DRE2N/DungeonsXL#107]
everything is in the title ;)

and if you doesn't have time I can try to made it...

**Comment by Sataniel98** [comment]
DungeonsXL shouldn't need specific support for Cauldron (execpt maybe some bugfixes for 1.7.x as it is not tested with it anymore), but BRCommons (which is a shaded dependency) will need an MCP implementation at least for the PlayerUtil:
https://github.com/DRE2N/BRCommons/tree/master/src/main/java/io/github/dre2n/commons/util/playerutil
This code might look a bit weird because it's copy / pasted from a different context

**Comment by lord44210** [comment]
How can I do an MCP implementation?

**Comment by Sataniel98** [comment]
This is one for Bukkit's mappings for 1_7_R4:
https://github.com/DRE2N/BRCommons/blob/master/src/main/java/io/github/dre2n/commons/util/playerutil/v1_7_R4.java
It also needs to be recognized and an Internals enum entry:
https://github.com/DRE2N/BRCommons/tree/master/src/main/java/io/github/dre2n/commons/compatibility

**Comment by lord44210** [comment]
ok thanks you a lot ^^
