### ISSUE TITLE
QUESTION: Ways to reward player?

### ISSUE THREAD

**Issue by MeDavoo** [DRE2N/DungeonsXL#1120]
[QUESTION] 
Hi, I'm loving your plugin but I was wondering if [with keep invetory when entering dungeon off] ayway to bring back items from dungeon without using the rewardchest? 

As in mob drops that when collected are added directly into rewardinventory and after leaving you can get them all without using or interacting with a rewardchest ? 

Thank you so much in advance :D

**Comment by MeDavoo** [comment]
Like i was thinking maybe it would be cool to have a command that lets you add stuff to the RewardInventory, like that when mobs are killed or stuff happen they could get rewards or smth :D

**Comment by MeDavoo** [comment]
Or better yet anyway to add quest rewards directly to rewardinventory to receive when the dungeon ends?

**Comment by Sataniel98** [comment]
Hi, sorry for the late reply. I plan to add a "reward sign" that can be triggered like any other sign when I get back to working on this plugin, so that could for example give rewards directly on death of a specific mob if it has a mob trigger. I'm not sure if a command would be the way to go here as this opens up a whole lot of "then why does X not have a command?" questions, but an addon should easily be able to achieve this.
