### ISSUE TITLE
DugeonXL triggers and configuration files

### ISSUE THREAD

**Issue by ajisfree** [DRE2N/DungeonsXL#134]
I generaly understand how the config files work for dugeons and and floors, but I having trouble because I dont know exactly where they need to go. Or what they need to be named. 

As for some of the triggers, I cant seem to get them to work either. For example I have a room that spawns mobs, the player(s) need to kill the wave of mobs and then Im trying to get it to spawn another wave with the wave sign and trigger but its not working for me. After 4 waves have been completed I wanted it to open a a redstone door using the Redstone Sign with the Trigger (P 0/4) Any guidence on how to complete this task?

**Comment by Sataniel98** [comment]
One wave is usually all mobs in the floor, so you have to tell the plugin not to check for the mobs in your room that should spawn after some waves with a progress trigger.

For the door, you should just use the locked door feature: Place a [door] sign attached to the door and add your trigger as usual in the last line. Note that door signs used to be broken and have been fixed in recent dev builds.

Files:

The floor configurations of dungeon floors are named config.yml and their location is:

_DungeonsXL/maps/{name}/config.yml_

Dungeon configs are not connected to maps. As you see in the example, the included floors are specified in the configuration values. The file name just specifies their ID.

In v0.14.x and lower, the path of dungeon configurations is:

DungeonsXL/dungeons/{name}.yml

As of v0.15.x, the path is:

DungeonsXL/scripts/dungeons/{name}.yml

I hope this helps a bit, feel free to ask further questions :)
