### ISSUE TITLE
Impossible for normal player to interact with interact sign

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#140]
Hello, 

While we are playing in a dungeon, there is an interract sign. I'm OP on my server and i've not problem to trigger interract sign. But for normal players, they can't (many try in different condition : Group, alone, etc...). 

There is two interract sign : one to change blocks and another to call a MythicMob's mob. Same problem in both cases. 

Any clue?

**Comment by Sataniel98** [comment]
Just a guess, but there is an option called "spawn-protection" in the server.properties file. By default, it protects all blocks in near by the spawn with a radius of 16. This feature also cancels all interaction events of Bukkit as far as I know. It's a Vanilla feature and usually redundant for CraftBukkit servers because most server owners use advanced protection plugins like WorldGuard anyway. Does it work if you set it to 0? If not: Is there an error log in the console? If still not, please provide some details about the signs you're using.

**Comment by Tiplish** [comment]
Ok thx for the answer. I will try it this afternoon.

**Comment by Tiplish** [comment]
Hello, you was right :) It was the problem. Now i can use Interract sign if my dungeon is not next to the spawn point. Thx

**Comment by Sataniel98** [comment]
Glad to hear that :)
