### ISSUE TITLE
CAliburn API

### ISSUE THREAD

**Issue by Francisco-Carvalho98** [DRE2N/DungeonsXL#199]
Hey, my problem right now is very simple lol.
I simply dont know how to install caliburn, not sure what to do with it. As you might be able to tell im not very experienced with this kinda of things..
Sorry for troubling you.
Thanks in advance

**Comment by Sataniel98** [comment]
As a developer or as a server owner? As a developer, my Maven repo is http://feuerstern.bplaced.net/repo and the group:artifactId is io.github.dre2n:caliburn. You can download the jar file [here](http://feuerstern.bplaced.net/repo/io/github/dre2n/caliburn/)

If you are a server owner, you do not need to do anything at all. Caliburn is integrated in DungeonsXL. If you want a nice way to manage your Caliburn items instead of directly in DungeonsXL where you need them (e.g. in class scripts), you can use [ItemsXL](http://feuerstern.bplaced.net/repo/io/github/dre2n/itemsxl/), which is a Bukkit plugin that implements Caliburn. However, it is in no way necessary to install ItemsXL in order to use DungeonsXL.

Note that Caliburn required Minecraft 1.9 or higher in order to work. If you use DungeonsXL with 1.7.9-1.8.x. it will use the old, deprecated deserialization util. Information are available [here](https://github.com/DRE2N/DungeonsXL/wiki/legacy-support#caliburn-integration).

**Comment by Francisco-Carvalho98** [comment]
Yes, we are just trying to implement enchantments and certain potions into classes. We assumed that couldnt be done with the normal config. I've tried Itemsxl as well, but i must be doing something wrong then.

Thanks alot and great plugins you have!

**Comment by Sataniel98** [comment]
Thank you for the kind words, is your problem solved?

**Comment by Francisco-Carvalho98** [comment]
Alright so we have managed to successfully create a custom item and have the classes pick it. We noticed it references it by the file name and not the "type", which answers my question of it having to be numerical or not. Great stuff. We are in a test phase of adding new stuff to our server. We have been around for over 6 years, economical/town based server, but nothing better than some dungeons, quests, new mobs to make it feel like new! Thank you so much again.

**Comment by Sataniel98** [comment]
In fact, this plugin has originally been created for a Factions/building/PvP/RPG server which is around since late 2011, so probably something relatively similar to your server :) Feel free to ask if you have any further questions.

**Comment by Francisco-Carvalho98** [comment]
I mean like, since we never had it, its new for us haha. We are from the world of eldin, founded december 10th 2010! We our one of the older server around for sure. Thank you I will!

**Comment by Francisco-Carvalho98** [comment]
Do you happen to know how to add potions to dungeons classes? Does it have to be through Itemsxl as well? Thanks in advance.

**Comment by Sataniel98** [comment]
You can always just create the item ingame and create a YAML representation with /ixl serialize if you are not sure.

**Comment by Francisco-Carvalho98** [comment]
We have tried that, but when we convert the serialized config into an actuall new item, it doesnt recognise the item. Our problem is trying to figure out how add an effect to potions. We cant get any effects to potions.

**Comment by somrune** [comment]
when you serialize. do you get something like this?

    ==: org.bukkit.inventory.ItemStack
    type: LINGERING_POTION
    amount: 25
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing

because this seems to work for me perfectly every time, but you can't just copy and paste it from the serialized file into you class file, you need to make sure it has the same amount of spaces everywhere (which tends to screw up with copy/paste and you need to add them yourself)

**Comment by Sataniel98** [comment]
Is this solved?
