### ISSUE TITLE
dxl bug report.

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#215]
When I use the dxl plugin, there is a bug where a block under a sign can be destroyed  even if it is protected by the residence or worldguard plugin.
I would like to know how the wave 'sign' mechanism works in detail.
First, I would like to know how exactly wave sign interact with nearby mobspawn signs,
and also wonder how I can control the detail about the waves.
lastly I couldnt make my boss spawn work when I had the wave progress as the trigger(condition) so I would like to know learn about that as well.
And plesae support Mythic 4.0.1.
Our current Minecraft version is 1.8 and the plugin build is 0.15.7 (lastest). Thank you!

**Comment by Sataniel98** [comment]
Hi,
Which signs are you talking about? Global or dungeon signs?

When triggered, the Wave sign respawns all mobs spawned by ExternalMob or Mob signs. You can let it increase the amount of mobs that spawn with a multiplier. It is supposed to be used together with a wave trigger that triggers whenever all DXL mobs are killed. Progress triggers can trigger specific signs when a specific amount of waves or floors is finished.

DungeonsXL supports all custom mob plugins that provide a console spawn command with location, world and mob type parameters. MythicMobs should be registered automatically.

**Comment by Ecilpse** [comment]
Any signs on any world.

**Comment by Sataniel98** [comment]
Residence and WorldGuard won't work in instances.

**Comment by Ecilpse** [comment]
This problem occurs in non-instant worlds as well such as the spawn.
Residence was just one of many examples. I am currently using the GriefPrevention Plugin in one of the servers with dxl. However, this problem(block under any sign becomes breakalbe no matter what kinds of protection is given to it) occurs on both GriefPrecention Plugin server and a non-GriefPrevention Server(such as skyblock).

**Comment by Ecilpse** [comment]
Bump?

**Comment by Sataniel98** [comment]
Was able to reproduce it for dungeon sign, but not for global signs.

**Comment by ghost** [comment]
I can confirm, it works for global signs too. I thought was WorldGuard or Craftbook buuut... I've just find this issue

**Comment by kuohsuanlo** [comment]
Is this going to be fixed in the near future?

**Comment by ghost** [comment]
No it won't. I spent months (almost a year actually) waiting for some severe bugfixing but it didnt' happen. My suggestion is to move on with another plugin as he doesn't care so much about this plugin even if he says otherwise. Not worth it, trust me

**Comment by kuohsuanlo** [comment]
I think I could just fork it and build my own one. I've found the part the not compatible to GP. 
No need to blame the author and collaborator. Everyone has different plan tho.

**Comment by kuohsuanlo** [comment]
Is there any temporary substitute plugin for this ?

**Comment by Sataniel98** [comment]
There's a plugin called instances, but it has different goals as far as I know. I don't really appreciate how you @Zughy imply that I lied about my work schedule, which is not the case. I told you clearly that I am unable to fix due dates since I am working on multiple plugins, currently don't run DungeonsXL on my own server and am not interested in placing myself under any obligation or even commercializing it. In general, I am still an active developer. I did about one commit per day last year, which isn't that bad in my book. If you had a look at the work that I already contributed to DungeonsXL, you'd realize it's way too much to drop it. For my Factions / RPG server, a well-working factions plugin is simply more important than a dungeons / mini game plugin, no matter how much I actually care for it, and that's it. DXL is supposed to be my next and last major project once FactionsXL is done.

**Comment by Sataniel98** [comment]
That should be it. Build 9 contains the fix.

**Comment by Tiplish** [comment]
Just to say, don't care about trolls, on my server, everybody love your work and if it's not perfect, many other plugins are worse... Continue, you have our support !

**Comment by Sataniel98** [comment]
@Tiplish <3
![](https://memecrunch.com/meme/BEAOT/you-da-real-mvp/image.jpg)
