### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Rocsapocsa** [DRE2N/DungeonsXL#218]
Helo, im new to this plugin and i want to get some advice how to setup on my server.  Can I make a dungeon entry in my main world and the dungeon in the dungeon world, and is there any way to create an entrance fee like a key or something like that.

**Comment by Rocsapocsa** [comment]
Can I add the entrance to a npc?

**Comment by Rocsapocsa** [comment]
oh, and the last and main question, how to keep the inventory in the dungeon world? I don't want to use classes so it's very important for me to keep my players inventory.

**Comment by Sataniel98** [comment]
You can make a portal to a dungeon in the main world with /dxl portal. Use group or game signs to bind it to your dungeon. Check the keepInventory game rules to let your players use their own items and requirements for what you call the "key". The API allows you to customize this entirely if you can program a bit. Details are available in the wiki :)

**Comment by LordDayradon** [comment]
Since this thread is recently active, I thought no need to create a new one.  I also am new to this mod and have a question.  For game types...is there a more detailed description about them I can read.  not exactly sure what appocolypse is, I understand the concept of adventure vs quest, But are some commands/functions not available in certain game types? like "critera: obtain item to advance to treasure room",  would only work if game type was set to Quest? and would not function  if  it was set to DM or adventure?  I'm guessing that the game type simply sets up some basic configs in the level config that relate to the game type and is more important in DM vs adventure? but I could set it up as adventure, and make it a DM with all the correct signs?  Sorry I just found the wiki lacking in this area.

**Comment by Sataniel98** [comment]
Each game type overrides a few game rules (for example, PvP is always enabled in PvP game types). They don't influence if signs work or not. I added game types mainly for the purpose to have interchangeable framework conditions in one dungeon. You can create multiple ready signs in a lobby that lead to quite different games while you only need to setup one single config. Players can decide themselves if they want PvP and friendly fire in a mob wave based game - depending on the ready sign they choose.

Detailed information about what they do is available here:
https://github.com/DRE2N/DungeonsXL/blob/master/core/src/main/java/io/github/dre2n/dungeonsxl/game/GameTypeDefault.java

The values inside the brackets refer to the ones beneath.

**Comment by LordDayradon** [comment]
Thank you for the quick response.  It is exactly what I needed and explains a lot. Thank you.
