### ISSUE TITLE
floor config - break/build blocks - Question

### ISSUE THREAD

**Issue by LordDayradon** [DRE2N/DungeonsXL#221]
If I enable building/breaking of blocks, after the dungeon ends, when it is next played is it restored to it's original state, or does it now contain the added/removed blocks from the previous match?

**Comment by Sataniel98** [comment]
It's restored to the original state. That's the purpose of this plugin :)

**Comment by LordDayradon** [comment]
If you don't mind me reusing this thread (please let me know if you do)  I am having problems with portal.

I can 'sometimes' get them created.  sometimes they just don't show up.

1. During creation when it says  click the frames, is it based on top-left bottom right format?

2. I have been mainly trying creating a frame, with inner cubes empty/air.  I have tried clicking on the inside of the frame on left, then on right.  if it creates the portal, the texture ends of facing the frame and not outwards.  I believe I have tried clicking on the face of the frame that faces outwards and it seems to have the same result

3.  Is there a mandatory size for the portals ie: will a 1x2x1 work?  do the blocks on the inside of the frame have to be solid or something other than air  (scanned the portal jar and saw some getBlock != Solid type stuff and vice-versa)

4. lastly, any of the portals that I  have successfully created,  after joining a group, then joining the game, walking into the portal has always taken me to the END of my main world. PITA.  I read another issue that you mention something like " are you sure your portal is setup correctly".  I can't seem to find any details on how I 'setup' or adjust the 'setup' of a portal.  I'm sure I'm missing something (actually lots of somethings)

*I should note that the test map I made has a lobby sign, but I have not placed a start/end/ready/classes sign yet as I'm only testing and learning the basics.  I also had not created the dungeon config or floor config yet (  that's today's testing - with a floor config for PvP LMS  (assuming I can get the portal to take me there successfully)

**Comment by Sataniel98** [comment]
One issue per issue is actually how it is supposed to be done, but I don't really mind.

1. It should just make a square (or cube) between the two corners, doesn't matter what you click first.

2. That's because portals have a data value for facing. I don't know why - glass works fine without it. DXL should calc the data value based on your angle, but even if it fails, you can still fix the portal with WorldEdit.

3. The size does not matter. I'm not aware of any checks like that.

4. Not sure about this. I have no idea why it would take you to the end world. Is it possible that you have other portal plugins installed that might interfere?

* That's okay, it should work even without a lobby sign and use the Vanilla world spawn instead and configs are not necessary for it to work in general.

**Comment by LordDayradon** [comment]
I'll use separate threads per issue going forward. :)

Well it's good to know I can use WE to fix the orientation with out breaking it.

re: 4  I don't believe so. Other than the standard load out could it be MV core or WG? All i can think of. 
My Plugins:  (running on spigot-1.11.2.jar)

Vault
Dungeonsxl0.15.6
Multiverse-Core 2.5
PEX 1.23.4
Worldedit 6.1.5
Worldguard 6.2
ChatEx
