### ISSUE TITLE
Sign ExternalMob with Citizen {Issue}

### ISSUE THREAD

**Issue by KevinBaselTheAnalyst** [DRE2N/DungeonsXL#235]
I copy a link of an Issue that you have resolved to me just because I have another question about it, dunno how to reopen it and I didn't want to write a double post. 
You can find my question as the last post here, thanks:

https://github.com/DRE2N/DungeonsXL/issues/232

**Comment by KevinBaselTheAnalyst** [comment]
Bump

Any news?

**Comment by Sataniel98** [comment]
Not yet. You do not need to bump issues, they won't disappear

**Comment by KevinBaselTheAnalyst** [comment]
Sorry didn't know that. Thought you didn't read the post.
I'm so happy of this plugin that I want to start to build my Dungeon as soon as possible!!
So let me know when you have news. xD
Cheers

**Comment by KevinBaselTheAnalyst** [comment]
Hi Sataniel, how's going?

Just to understand....: there is an issue with Citizen that you are trying to fix with codes, or it just the set up that I've made wrong?  Because if I have to wait more for you coding, I start to make the Dungeon differently because players are asking me to play, and then when you will be ready I will change for sure!

Let me know and good work!
Cheers

**Comment by Sataniel98** [comment]
I think it might have to do something with the method how I'm copying Citizens. Maybe the gamemode isn't copied and it sets the Citizens mob to creative. But I'll have to reproduce it myself before I know it for sure.

**Comment by KevinBaselTheAnalyst** [comment]
Hi Sataniel! How's going?
I saw that you've added the Bug label, so is that confirm as a bug?

**Comment by Loivado** [comment]
Hi, I may help out with the repro a bit here. But it's acutally pretty basic what happens. The copied NPC doesn't have a ID when selected in the dungeon. 

And btw did you find something out already, as the last response was a while ago already? :/
Is there maybe an old version with working NPCs? As a workaround for us?

DXL Version: 0.15.6
Server Platform: Spigot 1.9.4 (git-Spigot-c6871e2-0cd0397)
Related Plugins: Citizens (2.0.18 SNAPSHOT-1371), Denizen (1.0.1-SNAPSHOT - 1630 CORE:1.15-Build77)

Repro:
- Create a fresh Dungeon.
- Go in Edit Mode. /dxl edit <name>
- Set Signs for Start, Leave, Lobby, Ready 
- Create a new NPC with Citizens. (/npc create <name>)
- OPTIONAL: Modify the NPC a bit, either asignee a script, modify it to a sentry or something else. 
- Set a Sign for the NPC [ExternalMob] | npcId | 1,1,CI | range
- Save the Dungeon. (/dxl save)
- Test the Dungeon. (/dxl test)
- Go to the NPC.
- Select the NPC with citizen command. (/npc sel)
- Read out the NPC id from the NPC you selected. (/npc)

Currently:
- You can't read out the NPC Id of the just selected NPC.  
- All related Citizens and Denizen options for the NPC aren't applied for the NPC as there is no linked ID I guess. 

Expected:
- A Copy of the NPC gets created, which as a "linked" ID to the oringal NPC, to have a dependency for it's citizens and denizen modifications.

**Comment by Sataniel98** [comment]
Citizens has one ID per NPC, so I cannot use Citizens' registry for the ones that actually spawn in instances without spam-bumping IDs in Citizens. That's why DXL has its own registry and copies the mob from the Citizens registry. It is totally intended that these mobs do not have an ID in the Citizens registry. Plugins that save data per Citizens mob in their own databases instead of the usual Citizens data won't work with DungeonsXL. Everything else that differs between the template created by Citizens and the DXL copy, like missing traits, wrong skin or whatever is because DXL doesn't copy it yet. That's still an important point on the to do list.

**Comment by JennaDiamonds** [comment]
Any progress on this? Still Waiting patiently for the "missing traits, wrong skin or whatever is because DXL doesn't copy it yet." part :)

**Comment by Sataniel98** [comment]
First of all, thank you for your patience. I have indeed rather good news. Development slowed down a bit in the last weeks since I have a good bit of pressure to get an update for another project of mine finished, but I'm positive I have finally found the issue. Copying traits seems to work fine now. All other things that didn't use to work - like skins - should be fixed as well since it turned out to be an issue with applying the data to the NPC, not actually copying it. However, I noticed another bug while testing. The Citizens NPC wasn't able to hurt me in a no pvp dungeon because it was regarded as a player instead of an NPC. Fixing this wasn't much of a big deal, but I can't guarantee there are no other issues at all caused by Citizens NPCs being regarded as players yet.

If you'd like to, you can get the latest dev build [here](http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/). 0.16 no. 8 and higher include all fixes for Citizens I've done until now.

~Best regards

**Comment by Sataniel98** [comment]
I'll close this since other issues concerning Citizens, perhaps because they are regarded as players, are not technically connected to this one and should get a separate one. Please feel free to submit reports if you experience issues :)
