### ISSUE TITLE
Offline players do not leave properly when the server stops

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#240]

**Comment by ghost** [comment]
Dude, seriously, a severe open since March 12?
I got it, you suggest people not to run the plugin in a public environment, but a bug like this is fucking bullshit. THAT should be the first thing you should care about in a plugin like this. I'll tell you more: if a player logs out, it bugs itself too. And yes, I've tried the 0.16 dev build and no, it still doesn't work. I'm really tired to have this plugin as the only choice available to create dungeons. I've spent weeks to create a fucking masterpiece with events, triggers, bosses whatsoever, our players love it, but HEY, I can't allow people playing that because HEY if someone goes offline whilst in a dungeon, sayonara and enjoy the bug. And no, your "timeUntilKickOfflinePlayer" dosn't work either. 0, 60, 120, nothing.
I cannot even fix it at backend with Denizen, I mean, holy fuck, are you really at least a tiny little bit interested to keep going with this project or not? I mean, you could be the only person releasing a dungeons plugin, idolized by every RPG server but no, nada, batsu, basis is shit.
And, yes, I do am angry right now, as I've just flush hours or work and A LOT of players and potential donators. Christ fuck, not even the effort to change wiki signs, it took you months. People had to guess how to write a sign, SERIOUSLY?
You don't have time? then close it, at least other people won't waste their time as I did

**Comment by Sataniel98** [comment]
I will not tolerate any kind of offensiveness. Minecraft is no business for me. It's nothing but a game, freetime activity. I work on my projects whenever I want. You have no claims against me and no right at all to be triggered.

**Comment by ghost** [comment]
No right at all? Really? I'm just telling you what I've seen in these months, AKA nothing. My team and I waited for half a year for something it doesn't even work. And no, it's no offense, it's the truth. How can you expect people could use this plugin if they can't even have players to join as decent human beings in a dungeon without finding them stuck in a never-ending loop inside the dungeon itself? Dude, are you serious? It should be the first thing you should care about, it's like having skywars and don't bother about what happens to a player when falls down. Are you offended? Not my problem, as you're giving something to the public with several issues, not even caring about it. If the [redstone] sign wasn't working, I'd not be here complaining. I'd put a [block] sign et voilà, who cares, let's open a ticket and that's it. But, again, a CORE ASPECT hasn't been working for more than half a year and you said (to me as well as other people) that "you're working on it", that "you're close in terms of development". That blatantly is bullshitting people so yes, I have every right to feel like that. Moreover, the dev builds don't even appear on github, my devs can't even take the latest code and add stuff, for fuck sake.
Block me, do whatever you want, I don't care, I had the urge to express myself; sayonara

**Comment by Sataniel98** [comment]
How is it my fault that your developers aren't able to switch the branch? All code is available, what you stated is plain wrong. I told you I'm not talking in units of time but in units of development progress. That being said, I am not able to offer ETAs or anything. I never "bullshitted" people. I never pretended this was meant for a production environment or that a final version would magically be available five years after this project started and two since I took over the development. I openly stated the opposite. If this doesn't match your business plans, I'm sorry to hear that.

**Comment by ghost** [comment]
Ok, then, without swearing against anyone: your plugin cannot be used due to players getting stuck when they log out. That happens if they wait more than 60 secs to log in again; that said, `timeUntilKickOfflinePlayer` doesn't work. I suggest you to fix that problem before anything else, or the whole effort you're doing would be completely useless. In  the meanwhile, you could just disable that and make players run a /dxl leave command if they're in a dungeon when leaving/when server stops.
They'll lose their progress, but that's a lot better than being stuck in a world without any chance to leave (/tp, /warp etc. don't work, the player gets tpped in a few ticks inside the dungeon again). <= That happens if they die inside the dungeon after the log in (after the 60 secs). If you want, I can open a separate ticket.
For the ones using denizen: that would do the fix, already tested
```
leavedungeon_events:
    type: world
    events:
        on player quits:
        - if <player.world.name.contains_text[DXL]> {
            - execute as_op "dxl leave"
            }
```

My fault on the branch thing.

**Comment by Tiplish** [comment]
Hi, when player are stuck, they can't perform the /dxl leave command?

You say that you use Denizen. Is it not possible to prevent this issue by creating an event when server restart or when player disconnect, force them to perform /dxl leave? 
you could trigger, for example, " on player quit " in Denizen and check if player are in DXL dungeon. I'm quite sure that it's possible, with a developer team like yours, to put a fix script with denizen in the meantime as Sataniel fix it definitively. 

On our server, of course DXL is not bug free and sometimes, it makes us loose a lot of time. But less than develop by ourselves a plugin like this.

Moreover, as i can see, we don't pay him for his work. Every time he spends on this plugin is a gift for us. Stop blaming him, it's not fair. If you are a developper, why you don't suggest to help him to resolve this issue ?

**Comment by ghost** [comment]
About Denizen: that's exactly what I said in my latest post.
Actually, I'm no developer, I study languages and literature and I should be the storyboarder. Still, being the founder, as we can't provide all the features we'd like, I've been learning how to script with Denizen (well,  I know a little bit of java and C# too, but whatever). That actually thrills me and you have no idea how many plugins I fixed with that one because their devs just disappear. Still, what it bugs me is that this plugin, right now, can't be used anywhere. It's not limited, it's a no-go. And it's bad, it has A LOT of potential. I've been using that for months, all those triggers animations you can do, events, it's just WOW, gratz on that, sincerely.

I can't help him saying "fix this line" due to, as I've previously stated, I'm no dev. But if you want a couple suggestions, I'd say:
- open a discord server: as far as I understand, you've been developing many plugins and you do have a server. You could merge those things creating separate channels where people can come both for asking help both for playing. And it's free advertising, a big plus for your community; moreover, if someone from your community knows where flaws are, he could be serve as helper. This is a method used by some big shots in the mc developmental environment, like MythicMobs, Denizen and WorldEdit. Of course this doesn't mean you or any other helper must be available 24/7, it'll  just facilitate a lot the work. Besides that, people will feel closer to you, kind of a bond: it's nice, for both sides (not speaking by hearsay). 
- create a showcase channel on discord and/or on your site: people would be more attracted by the idea that their work could appear online (and they can decide if share that with others or, dunno, just put the link of their server)

Besides being a dick, I can also be helpful. I also know by heart the wiki, so if you'd need any kind of support, I'd be glad to help

**Comment by Tiplish** [comment]
Ok i understand but, to be honnest, run a server without some real developper is quite hard. I know how frustrating it could be when plugins stop working and so our player complaining about us. 

But that's the game... It's not possible to say to player to leave properly the dungeon before disconnect?

I use DXL since more than one year and player are not stuck in dungeon when they disconnect in it. They are just TP back to our spawn (and keep the stuff they get in the dungeon). Have you a plugin which manage spawn? Like essential?

**Comment by ghost** [comment]
Asking that to a player is just... no. Our role is to prevent that kind of damage, because, for instance, if someone crashes because, you know, it's minecraft, that's not even their fault.

Yes, I have essentials and when players disconnect, when they log back they are in the same location they were before dc. Like a single player minecraft, I haven't forced any spawn

**Comment by Tiplish** [comment]
Ok because on our server, when someone is in a map which doesn't exist, he is tp back to the main default spawn. I will try some test. Maybe i could find a way to avoid your problem for the moment.

**Comment by ghost** [comment]
The problem is, the map do exists. Just think about a player and I being in a dungeon: if I leave and wait more than 60 seconds before logging in again, I won't be considered by the plugin in the dungeon anymore, still I'd be exactly inside the dungeon world. And, if I die inside that world, I'm 100% stuck there, even if the other player leaves with /dxl leave.
Again: do you have any discord? I can provide you a lot more information than bothering you on github. That's not even the proper issue

**Comment by Sataniel98** [comment]
> open a discord server: as far as I understand, you've been developing many plugins and you do have a server. You could merge those things creating separate channels where people can come both for asking help both for playing. And it's free advertising, a big plus for your community; moreover, if someone from your community knows where flaws are, he could be serve as helper. This is a method used by some big shots in the mc developmental environment, like MythicMobs, Denizen and WorldEdit. Of course this doesn't mean you or any other helper must be available 24/7, it'll just facilitate a lot the work. Besides that, people will feel closer to you, kind of a bond: it's nice, for both sides (not speaking by hearsay).
> create a showcase channel on discord and/or on your site: people would be more attracted by the idea that their work could appear online (and they can decide if share that with others or, dunno, just put the link of their server)
> Besides being a dick, I can also be helpful. I also know by heart the wiki, so if you'd need any kind of support, I'd be glad to help

Sorry for the late reply, I didn't have access to the internet in the last days.

I do have a server, but it doesn't have DungeonsXL installed and its language is hardly internationally relevant, so I guess there are few to no chances a DXL support channel could have any benefits for it. Even though using Discord appears to be a convincing idea and surely the best for this project (since it is and will always be demanding to setup) I honestly don't know if I am able to "man" a Discord often enough to make it actually helpful. Since most of them are builders or moderators, there are no members in my server team who could help me out. I'd love to see DXL as a solid, commonly used project with great infrastructure, but it's just too much of a niche product to attract fellow developers and a community of users like MythicMobs does. However, I still have a vision of a roleplay extension to my server that I want to realize sooner than later, so I'll work on it. If you would like to help, please feel free to contribute to the wiki. Don't hesitate to add new pages with examples and explanations if you consider them useful.
