### ISSUE TITLE
MythicMobs custom levels

### ISSUE THREAD

**Issue by infered5** [DRE2N/DungeonsXL#280]
I'm wondering if it's possible for MythicMobs to have set levels. Our server works very hand-in-hand with MythicMobs' built in level scaling, so we only have to make one mob and then the level determines other attributes. From what I understand, it'll spawn MythicMobs at level 0 as default. Do I have to make new MM mobs at this specific level for each dungeon I'm making?

**Comment by Sataniel98** [comment]
DungeonsXL uses a system to support all mob plugins that provide a spawn command for command blocks / consoles. It can't support things that are very specific to a single mob provider like a level system. But you can just register the different levels as seperate mob providers in the main config and give them different tags, like "M1" for level 1 MythicMobs instead of the default "MM" with no level specified.
