### ISSUE TITLE
Mythic Mob possible bug 

### ISSUE THREAD

**Issue by azerty5** [DRE2N/DungeonsXL#320]
Hey, Sataniel

Think I may have found a possible bug when DungeonsXL hooks into MythicMobs. So if I upload anything above MythicMobs-2.5.11 it won't hook into DungeonsXL and I check on /dxl status. Not really a problem so I upload MythicMobs-2.5.11, reboot, check /dxl status, has the tick next to it so I to go into my Dungeon Mob Spawns from the sign killed it, Then I typed /dxl leave then when I try to play the Dungeon again throws an internal error at me:

https://pastebin.com/td9AnyAA

So I disable Mythichmobs-2.5.11 and get a higher version. Then it lets me leave and join the Dungeon every time but on /dxl status MythichMobs isn't hooked into DungeonsXL and my ExternalMob signs with MythicMobs on them don't work

**Comment by Sataniel98** [comment]
Note that /dxl status does not show if DXL hooked successfully into another plugin but if the versions of your plugins are confirmed to work together. Especially the support for custom mob plugins is intended to be as tolerant as possible, you can even register your own ones in the config.yml. Support for a mob plugin won't break unless the syntax of its command to spawn mobs with world and coordinate parameters changes. The issue is of course a bug I hope to fix in the forseeable future.

**Comment by azerty5** [comment]
Okay, thank you. Can't wait to see the plugin bug free. Great work, keep it up!
