### ISSUE TITLE
Boss is not spawning?

### ISSUE THREAD

**Issue by DogiWF** [DRE2N/DungeonsXL#324]
The boss spawning sign isn't working. It's an iron golem boss. When I join the dungeon, the other normal mob signs work (btw i write 10 but it only spawns 1) but this sign doesn't work. Here's the sign:

![2017-10-06_22 00 38](https://user-images.githubusercontent.com/20614198/31293954-caf21c56-aae1-11e7-91be-024d12698f4f.png)

**Comment by Sataniel98** [comment]
That may be because you put a delay of 100,000 seconds to the sign.

**Comment by DogiWF** [comment]
But if I do it like 10, that would spawn another boss 10 seconds later, right? I want it to only spawn one.
Also I did it 10 and tried it, but it didn't spawn a boss again.

**Comment by Sataniel98** [comment]
Yes, technically, it would, but only until the mob count is reached, which is one in this case.

> [ExternalMob]
> mob
> 10,1,MM
> D 75

translates to "run the spawn command for 'mob' of MM one time with the position of this sign with a delay of ten seconds when a player is 75 blocks close to the sign."

Also please check the console since it might say something useful depending on the external mob plugin.

**Comment by DogiWF** [comment]
MythicMobs and DXL gets enabled with no problem. No info about why the boss isn't spawning tho, I made the sign like you wrote too but doesn't work.

**Comment by DogiWF** [comment]
Oh, never mind. I think I solved it. MythicMobs version.
