### ISSUE TITLE
Players can't finish a dungeon if someone from their group leaves

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#327]
When they hit the sign, it tells them "You've completed blabla" (and not "you have to wait for blabla") but they don't get teleported back to the main world. They can  use /dxl leave, of course, but their rewards will be gone. Kinda pointless.
I have a denizen script executing /dxl leave on any player who leaves the dungeon (if world name contains DXL, then blabla), in fact their name disappears from the sign.

Map config: https://hastebin.com/afocuyuhoh.coffeescript

Kind of a severe...

**Comment by Sataniel98** [comment]
Note that the default value for timeUntilKickOfflinePlayer is -1, so provided that you do not have any settings in a different game rule provider (e.g. main config), players will never get kicked from their group at all if they leave and are therefore still supposed to reach the end. But I think I'll set the default value to 0 instead, since most users will rather need this.

**Comment by ghost** [comment]
Well, denizen executes /dxl leave for them if they log out, so that -1 shouldn't be a problem at all

**Comment by ghost** [comment]
Oh, ok, wait: someone put `timeUntileKickOfflinePlayer` on 60 in the main config.yml (...).
I changed it with 0 and now, even without the denizen code, it seems to work :) So I guess the bug appears when timeUntilecc. is more than 0..?

EDIT: also if I press "end" and the other one leaves

EDIT 2: Just kidding, the bug persists even with 0
