### ISSUE TITLE
Map is not Editable ..

### ISSUE THREAD

**Issue by Phoenixmrn** [DRE2N/DungeonsXL#334]
Working on a Multifloor dungeon. Made the 2nd floor and after exiting it I cannot return to it in edit mode. The "floor" sign i had does not allow me to move on to the 2nd floor. I can only get to it via /dxl play (name) and then its not playable. I am not sent to the spawn point and the mobs don't spawn.
The Map shows up in /dxl list, but when entering /dxl edit name it states the dungeon does not exist. I even tried renaming it..

[Save_Spawn.txt](https://github.com/DRE2N/DungeonsXL/files/1481299/Save_Spawn.txt)

![2017-11-16_23 46 56](https://user-images.githubusercontent.com/33745133/32934659-c1325844-cb29-11e7-834b-78aaa2cb93c8.png)

**Comment by Sataniel98** [comment]
Sounds like you entered the floor instead of the actual dungeon. Note that the dungeon name must be unique; if it's equal to a floor name, it's ambiguous.

**Comment by Phoenixmrn** [comment]
Ok so lwt me make sure i understand. I can have a config file named Save_Spawn, but the first playable level cant be named that. The first mao has to be Save_Spawn_01 for example?

That would make sense as to why the floor at the end of floor 1 doesnt work.

However why is that prevting me from being able to edit save_spawn_02?

**Comment by Sataniel98** [comment]
I'm not sure why you can't edit the map, to be honest. Try restarting (not reloading) your server and check if it still doesn't work. If it doesn't, look for stacktraces in the console.

In general, all maps get one dungeon automatically sothat they can be played without the need of an addition dungeon script. That's why there is always a dungeon named like the floor. So, if you name a scripted dungeon just like a floor, the command to play both dungeons - the one with multiple floors and the dungeon with just the first floor - will be the same.

However, even your scripted dungeon ends after one floor since the script is lacking values:

```
# How many floors shall be selected randomly from the list before the player gets teleported to the endFloor?
floorCount: 3

# If true, the floors will get removed from the list when finished
# sothat one floor cannot be selected multiple times.
removeWhenPlayed: true
```

If players make it to the floor sign, they usually get teleported to a random floor from the list randomly. This happens until the floorCount is reached. If set to true, removeWhenPlayed ensures that all floors from the list are played only once. If false, the floorCount may be as high as you want because the floors from the list can be played multiple times. Since you probably set up a specific order with floor signs and want all of the floors to be played, you should go with "3" and "true".

**Comment by Phoenixmrn** [comment]
Thank you for being very responsive. I will try these when i get home.

**Comment by Phoenixmrn** [comment]
Ok I updated the config, i an edit the worlds but now i cant join the dungeon as a whole.
[latest.log](https://github.com/DRE2N/DungeonsXL/files/1485889/latest.log)

[Save_Spawn.txt](https://github.com/DRE2N/DungeonsXL/files/1485891/Save_Spawn.txt)

**Comment by Sataniel98** [comment]
And how does your group sign look like?

**Comment by Phoenixmrn** [comment]
[DXL]
GROUP
Save_Spawn
1,3

then just Group shows up in green

**Comment by Phoenixmrn** [comment]
/dxl play Save_Spawn and /dxl play d Save_Spawn doesnt work

**Comment by Sataniel98** [comment]
The syntax is /dxl play Save_Spawn. It's weird that the global data doesn't save; it seems to be corrupted. Try deleting the data.yml and place the signs in the main world (not the ones inside edit worlds) again.

**Comment by Phoenixmrn** [comment]
https://hastebin.com/ihaxumugol.vbs
After restarting it still inst listing the Dungeon as a dungeon just the individual maps
After creating the signs it still did not show me joining as a group for "Save_Spawn" and said the dungeon doesn't exist when attempting to enter the portal

**Comment by Phoenixmrn** [comment]
![2017-11-19_21 32 37](https://user-images.githubusercontent.com/33745133/33002418-5aca89e2-cd71-11e7-9214-d438be7516cd.png)

So It says 1 dungeon exists and 4 maps, but only 3 maps have been made and then doing /play says the dungeon doesnt exist.

**Comment by Phoenixmrn** [comment]
Ok so apparently it breaks if you build the config file to have more maps then currenly exist. So you cant test as you go perse. Also in figureing this out it deleted map 2 and replaced it with a new map, but that map also now exists 2x

**Comment by Phoenixmrn** [comment]
Currently there is only 1 map in the folder, but doing /dxl still states there are 2. I gotta take a break from messing with it tonight

**Comment by Phoenixmrn** [comment]
So i found what is corrupting the map. If you are editing the Map. and someone TPs to you, another staff, then you leave the map with them in it. The Map corrupts. You can no longer use /dxl edit (map) as it sends you to a new blank map. It then corrupts it so all maps are lost.

No idea how to stop or fix it after it happens.

**Comment by Sataniel98** [comment]
Do not TP into DXL worlds. Use /dxl edit instead.

**Comment by Phoenixmrn** [comment]
I totally understand hiw easy that sounds. But wechave a dozen staff they dint know where someone is so accidents happen. I just wanted to make you aware of what cmcan cause the map to break.

**Comment by Phoenixmrn** [comment]
Im going to close this thread as the initial cause has been explained.
