### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fenix12585** [DRE2N/DungeonsXL#347]
Hello,

First, sorry for making this an issue ticket.  I have not found a bug, in the plugin, rather I just don't understand the wiki well enough. I am trying to work the groups. The way I am trying to work this is for a player to enter the lobby through an item or something, I can work that out with itemsxl or a plugin along those lines where the item will execute a command then be destroyed. However once the player enters the lobby, I would like them to be able to invite friends to join there group. I can't seem to get the group signs to work from within the lobby, is there some workaround to do this? I was hoping to make it so the first person in the lobby would be the group leader, and they can invite friends and everything from there, then when they are ready, start the dungeon. (Do I even need groups for this? I just want players to have control over who they play the dungeon with)

Thanks for your help! I understand this dosnt seem to be built in to dxl, but if not is there some kind of workaround I could do?

Also, I am trying to create a simple 1 floor dungeon where players keep the inventory they enter with. I see in the wiki where i need a dungeon config file. I am not clear how to create this.
I copy and paste the example and name it the same as the dungeon.yml in the scripts/dungeons folder. then when doing /dxl reload the console says 
`30.12 16:02:27 [Server] INFO The configuration file plugins/DungeonsXL/scripts/dungeons/Maze1.yml seems to be outdated. 
30.12 16:02:27 [Server] INFO Adding missing values... 
30.12 16:02:27 [Server] INFO The setup of dungeon Maze1.yml is incorrect. See https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration for reference.`

I have also seen in the FAQ where it says to create the config.yml under the map folder, so i put it there too, I tried with the file name like above or as config.yml. Neither work or give errors.

How can I set this up to work properly?

Thanks!

**Comment by Sataniel98** [comment]
Hi,
opening issues to ask questions is fine. In fact, I prefer having them here rather than in one messy thread over at SpigotMC.org.

ItemsXL is a plugin to manage custom items and to deserialize them from a YAML file; it won't help you with clickable items or something like that. However, there are several other plugins that do what you're looking for. Group and game signs are global signs that are supposed to be put somewhere next to an entry portal. They will not work inside a dungeon. If the players are supposed to play non-competitively together, one group and one group sign without any game signs per instance are sufficient. If you don't want to use portals, invitations and joining a group and a game can be done through commands (/dxl group).

Dungeons that contain only one floor do not require a dungen script. They are created "artificially" at runtime per map. This is because none of the settings that they provide can be applied to them. [DXL game rules are fetched from multiple sources](https://github.com/DRE2N/DungeonsXL/wiki/game-rules) and the sections inside a dungeon script exist sothat game rules don't need to be copied to each single floor of a dungeon with multiple of them since that would make modifying them a pain. In your case, add the values that you need for every dungeon (for example keepInventory and timeUntilKickOfflinePlayer) to the "default" section of the main config.yml and the values that are specific to each dungeon (like text messages) to the respective file located at "DungeonsXL/maps/{map name}/config.yml". Note that these files are supposed to look [like this](https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration) and that they shouldn't contain game rules you don't need.

I hope this helps. If you have any further questions, please feel free to ask.

~ Best regards, have a nice day and a happy new year :)
Sataniel

**Comment by fenix12585** [comment]
ok, that is helpful, but I am still struggling to figure out a way to make this work.
I would like a player to be able to invite friends to play a dungeon with them, but only from the lobby. So basically a player would trigger something that would have the console run the command to have them play the dungeon. This would dump them in to the lobby where I would like them to be able to invite friends to play together cooperatively. Is this something that can be done? Possibly with command signs or something like that?

**Comment by Sataniel98** [comment]
I'm not aware of any way to do this. The problem with command signs is that you can't have a parameter for the player to invite. The players would need to run the commands themselves.

**Comment by fenix12585** [comment]
Could I request that group signs be able to work from the lobby as a future
update? I am using dungeons in alternate manner and this would be very
helpful. For example, my first dungeon is called The Bandits Cave. I am
using mythic mobs in the normal world that drop a key fragment custom item.
These can be combined at a crafting table to form an item that will run the
play command for the player and bring them to the lobby. I need to find a
way for them to invite friends to play with from here, as there is no
portal or anything in the main world.

Also, you said the config files won't work for single level dungeons, Is
there a way to allow players to bring there own gear in to a single level
dungeon?

Lastly, I see  the loot tables, and the tutorials on them, but I still
don't fully understand how they work. As I am learning more about this
plugin, wouldn't it be possible to just put items in chests normally and
have the players distribute between themselves? Or will that not work, and
why?

Thanks so much for your time and patience!

**Comment by Sataniel98** [comment]
I am in general open to suggestions like yours. However, since I don't use DungeonsXL on my own server unlike other projects of mine like e.g. FactionsXL, it lacks a lot of care at the moment ;C I'm slowly working through bug reports now and again, but that's and will be it for the forseeable future. Feature requests are not very likely to get implemented right now unless I get pull requests - even if I like the idea. Sorry for that ¯\_(ツ)_/¯

The "dungeon.yml" config file won't work since it just links floors together and overrides / adds subsidiary game rules. Adding game rules should be done in the map's config in your case (or in the main config if they are supposed to work for all dungeons).

Less abstractly: Add a "config.yml" file located at plugins/DungeonsXL/maps/{your map}/config.yml and write
```
# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: false
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: true
```
into it. I guess you might want to have keepInventoryOnDeath true as well and to set an amount of lives / group lives until the player finally "dies".
```
# Amount of lives a player initially has when he enters a dungeon
initialLives: 3
```
or
```
# Alternatively, you can use group lives.
initialGroupLives: 5
```

Loot tables are not always necessary for item loot. I created this concept for multiple purposes, including stuff I haven't implemented yet like custom mob drops. If they could already be used for mob drops, they'd make this fairly easier. Just adding the items to the chest is fine of course, but the main reason to use a loot table instead is that it allows you to specify a percentual chance to actually get each item which a chest can't do. Plus, it might speed things up if you wish to have the same loot in many chests.

**Comment by fenix12585** [comment]
thank you for all of the help.   I understand about it not getting added,
but it does make things much more difficult, as you really do have the only
remotely good plugin for this... and by remotely i mean awesome... Would
you consider adding it as a job? I have hired people for custom plugins
before, this would just be a benefit to many people :)

If not, i totally understand, but i gotta try lol :)

**Comment by Sataniel98** [comment]
Well, I'm not working on it much because I don't have the time to do so. Thank you very much for your offer, I appreciate it, but money won't buy me any spare time. And even if I had enough time to work on your request, I'd rather fix the inconsistencies and bugs I couldn't iron out yet. Taking money for adding features before this is done doesn't feel appropriate to me.

**Comment by fenix12585** [comment]
I totally understand... Thanks for all the help!
