### ISSUE TITLE
Signs not working

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#360]
I can not interact with any signs. They can be broken by me however. Also my end sign dose'nt work.

**Comment by Sataniel98** [comment]
Did you include a ready sign to start the game?

**Comment by snowy6409** [comment]
Yes I did have a [Start] sign. But I can’t even interact with that one. It just lets me break the sign thats it.

**Comment by Sataniel98** [comment]
But do you have a [ready] sign? The start sign isn't that important, it just teleports you to the start sign location after triggering a ready sign. If yes, please tell me step by step what exactly you did after starting your server with DXL.

**Comment by snowy6409** [comment]
Yes I have a ready sign. Ok I just installed the plugin fresh. from setup at spawn I have a group sign. It works. The /dxl portal doesn’t so they /dxl start. It drops them into the lobby room with the class sign leave sign and ready sign. They have all become active (printing correct things) but you can’t interact with the signs or do anything. Is it  a problem with having multiverse

**Comment by Sataniel98** [comment]
Multiverse and DXL work fine simultaneously. Just make sure not to add the DXL_Game_* worlds to MV. Did you set spawn-protection to 0 in your server.properties?

**Comment by snowy6409** [comment]
Yes and even when I didn't set it to 0  we all oped so it wouldn't have mattered. It was just not letting us interact with the signs besides breaking them.  No, I did not add it to MV.

**Comment by Tiplish** [comment]
So your ready sign doesn't become an interact sign? But you have a Lobby Start Ready and End sign on your dungeon, that's right? 

Are you sure that when you have put these signs (Lobby Start etc...), you had a message "successfully put sign" or something like this? The person who put the signs have to have the right permission to do it.

**Comment by snowy6409** [comment]
Yeah

**Comment by Tiplish** [comment]
It's an OP player who have put the signs in the edit dungeon?

**Comment by snowy6409** [comment]
Yes It was me

**Comment by Tiplish** [comment]
Are you sure that you haven't more that 1 Lobby, End or other MAIN signs?

(I ask you this because i was facing all this case during my use of DXL :p )

**Comment by snowy6409** [comment]
According to world edit stats, I have 7 signs, Start,Lobby,Leave,Classes,Ready,End, and a mob spawn.

**Comment by Tiplish** [comment]
Have you try to change the position of your signs? I remember that one day, i put a DXL sign on a wall and the dungeon was stuck with normal sign (like you). I have just change the location of the different signs and it has worked. 

If you place again your signs, check that everytime, you get a successfully message. (It could give clue in the other hand).

**Comment by snowy6409** [comment]
I got successful messages but I will try placing them in different places again.

**Comment by Tiplish** [comment]
Maybe try with only the 4 mains signs at the first time (Lobby - Start - Ready - End), and test the dungeon :p

**Comment by snowy6409** [comment]
I will try that

**Comment by snowy6409** [comment]
It works in the new world. I am guessing it is something wrong with the other world or its signs. Also, how are the class files supposed to be configured? I have no idea and would like if on the GitHub or with the plugin there would be a single example class so I could figure out how they are set up in the file. The example for the classes script doesn't help in explaining how to use that information.  I also have no idea how to implement the classes. I have a sign with the [Classes] Test and a file test.yml but what do I put in the file to make it work. The wiki dosent exactly explain that.

**Comment by Tiplish** [comment]
Sorry i don't use DXL class, i use another plugin for the classes. I happy that you solve your sign problem o/

**Comment by snowy6409** [comment]
@Tiplish What do you use? Races and Classes? or something else

**Comment by Tiplish** [comment]
SkillAPI :)

**Comment by snowy6409** [comment]
Ah good choice

**Comment by Tiplish** [comment]
I just hope that the author stay active...

**Comment by snowy6409** [comment]
How do you allow them to take their items into and out of the dungeon

**Comment by Sataniel98** [comment]
https://github.com/DRE2N/DungeonsXL/wiki/scripts#classes

"If players should not play the dungeon with their own items but with a set inventory, class scripts are the way to go. Thanks to the CaliburnAPI / ItemsXL integration, DungeonsXL supports three different ways to store items in configuration files.

In a dungeon, a class can be selected with a classes sign."

For me as the guy who developed these things, it's sometimes hard to think like a beginner and to explain the things as detailed as they need to be explained. So if you don't understand anything, it would be really helpful if you could explain in detail where it's confusing to you. Classes are basically a list of items that the player gets when he triggers a class sign. You adjust these items in the class script and bring them into the game through a [classes] sign. If you instead wish to use the items the player got in the main world, you can set the keepInventoryOnEnter, -OnFinish, -OnEscape to true. In my experience, it might be worth to do this in the default section of the main config because these rules tend to be always the same in each dungeon on a server.
