### ISSUE TITLE
Suggestion, EnderChest, Bed, Dispenser Permission node.

### ISSUE THREAD

**Issue by kuohsuanlo** [DRE2N/DungeonsXL#417]
I would like to ask if you could add these three permission nodes.
I've read your source code and found it could be easily done by add a few line of coded,
implemented as a working version in the link below. 
https://github.com/kuohsuanlo/DXL/commit/da2e749a2faaa4e8542c655a1884b5f0670d9927

Thanks.

**Comment by Sataniel98** [comment]
I'll merge it if you make a PR.

**Comment by kuohsuanlo** [comment]
My version has been revised a lot. 
And I spent some time solving issue to compile the project, 
my version might not be suitable to make a PR.

**Comment by Sataniel98** [comment]
If you still have issues building the project, please feel free to ask questions and to report any inconsistencies that you notice. I reorganized some things and my repository for 0.16, and hope that it builds with as few effort as possible, ideally with no requirements but a valid installation of the JDK and Maven.

Since I don't know how experienced you are with Git: https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository This helped me a lot in the past ^^ It might be worth to maintain a branch that is synced with the mother project.

I can of course just make a commit containing the changes myself. But whenever it is possible, I prefer to let the actual author PR the commit sothat he (and his copyright!) is mentioned in the commit history.

**Comment by kuohsuanlo** [comment]
I totally agree with you. I compiled my own version just because of my limited time. I just cut down all library and dependency that I don't need such as glowstone, NPC, ...etc. And I do think using latest version is better. 

There is another feature I've hard-added because of my personal usage, which is "auto-ready and start" dungeon. Because players often forget to all click the ready sign. 
(In my server, the lobby and the dungeon stay in one map. So they keep reporting not being not able to harm the entity.) So I edit player teleport event when the targeted location is the dungeon game, it just force triggers the start function. 
https://paste.ofcode.org/fP2D588PYwKUw5A2GsJNrv


Also, there is a bug which could be re-do by 
1. join dungeon (not clicking ready-sign)
2. dxl group disband
3. player stuck in dungeon map
In this case, player can't leave the dungeon map but still considered not in a game, this can only solved by /dxl reload.
So I implement a force-leave command to simulate the /dxl reload. Just wondering is this problem being solved.

The above reasons is why I stuck in my version and the master thread.

**Comment by Sataniel98** [comment]
Is there any particular reason why you didn't use the built-in auto ready function (<- just noticed that's not documented very well, sorry for that :X)? Alternatively, you could add a distance trigger sothat your players don't need to punch a sign. I was not aware of the bug, thank you for the report :)

**Comment by Sataniel98** [comment]
@kuohsuanlo Still around?

**Comment by kuohsuanlo** [comment]
Yes, but I am busy tweaking my server and developing other plugins. 

Q : Is there any particular reason why you didn't use the built-in auto ready function
A : I think that's a long story. In short, I include the command into GUI rather than sign( my server is non-english server, English signs are not preferred for my scenario. Clicking "Start" in the ChestUI makes the ready sign a little bit redundant.
