### ISSUE TITLE
Importing Maps

### ISSUE THREAD

**Issue by architetto14** [DRE2N/DungeonsXL#422]
Hello, here I go again.

### Expected behavior
I want to  import a map into my server. I paste it into the maps directory inside the DungeonsXL directory. It is recognized and I edit it with /dxl edit [name]

### Actual behavior
Once imported, the map is recognized only as a map, however I imported all the files inside the map directory, that was recognized as Dungeon in another server. The problem is I can't edit this map, neither I can play it.

How should I set a Map as a Dungeon? I don't think this is a Bug, but I am ignorant and I wasn't able to find a solution on the wiki

Sorry for bothering you and thanks for your support!

EDIT: I can't edit even a map I just created. It doesn't find them when I try to edit, but I can play them.

**Comment by Sataniel98** [comment]
Did you use /dxl reload or restart the server after copying the map into the maps folder? That should be all you need to do to load these maps. What exactly happens when you try to edit one of them?

**Comment by architetto14** [comment]
Yes, I did reload the plugin, but I didn't restart the server. The map was loaded, but I wasn't able to edit it.

When I tried to use /dxl edit [map] it said that the map didn't exist. But when I used /dxl play [map](with the same map) it worked and I was able to play the map.

**Comment by Sataniel98** [comment]
Strange... may I know which message you received when it didn't work? Or was there maybe a stacktrace? Not trying to sound like a telephone company call center guy, but did you try turning it off and on again? ^^

**Comment by architetto14** [comment]
I received a simple "This map doesn't exist!". Yes, I tried to turning it off and on, but sadly it didn't work.

This evening I was wondering: in the known issues it is said that DungeonsXL is not compatible with Towny. We use a plugin called Feudal [https://www.spigotmc.org/resources/%E2%AD%90-feudal-50-sale-%E2%AD%90-kingdoms-gui-market-wars-professions-attributes.22873/](url)), could it the 'cause of the problem? I don't know, I'm just throwing ideas at this point. In my test server DungeonXL works fine, in my official server, where there is Feudal, it doesn't.

**Comment by Sataniel98** [comment]
Well, I don't know Feudal, so I can't say for sure if it is incompatible or not, but the issue with Towny was very special. Towny used to occupy edit worlds, keep them loaded and hinder DXL from saving them correctly. Most if not all Factions-like plugins don't do anything similar. Does the name of the map maybe contain any spaces or any other symbols that might break the syntax? It's weird that /dxl play works yet /dxl edit fails at a condition that seems to be more or less identical in both commands to me. I'm sorry for the problems, but it seems I'll need to make some detailed testing in order to fix it :/

**Comment by architetto14** [comment]
Hello. It took a while, but we found out what caused some major issues.
The plugin PerWorldInventory doesn't find the world (I suppose DXL_Edit_*, it's one of those that erase itself) and Multiverse find the world but says that it is not loaded. Moreover the plugin React cause many issues.

**About PerWorldInventory:**

my admin said this: it's a big error, but maybe if the Dungeon is always loaded it can be solved

**About Multiverse:**

it's not a proper error, it's more like a warning

**About React:**

We deleted his Database of World Config and the errors ceased. But when a new DXL_Edit_* is created React causes some minor issues

In the end the major issue was PerWorldInventory, while react gives some little problems, but nothing to worry about.

Considering all this, we fixed what we can fix and now DungeonsXL works how it's supposed to do. /dxl edit is not a problem anymore.

Thanks for your hard work and all your support!

**Comment by Sataniel98** [comment]
PerWorldInventory: See #155 - DungeonsXL might not be compatible with plugins that offer separated inventories per world. It can possibly be fixed by limiting that plugin to the static worlds with PerWorldPlugins.

Multiverse: I am using Multiverse and DXL simultaneously for a long time. You should not add DXL instances to DXL, but as long as you don't, there won't be any issues.

React: I've got to admit that I don't know this plugin. Since it is a paid plugin, there's nothing I can / want to do about it. Sorry for that :C

**Comment by architetto14** [comment]
No problem! You have been a great help. About react we're gonna fix it by ourself, also considering that there aren't big issues. Thanks for everything!
