### ISSUE TITLE
Mob sign doesn't work as expected

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#442]
### Expected behavior
Sign set up like this:
[Mob]
Zombie_Villager
5,3
D5

Expect it to spawn a total of 3 zombie villagers, with a 5 second delay between each one.

### Actual behavior
I get six entities, a mix of zombie villagers and regular zombies, spawning with little to no delay between them. The same thing happened when I put 3,3 and 5,1 on the third line. Sometimes it seemed I would get different numbers of zombies, (between about 5-7), but never the correct total number.

### Steps to reproduce
Try to make the sign as described.

**Comment by Sataniel98** [comment]
@FTOtter I believe this is a duplicate of #321.

**Comment by FTOtter** [comment]
It may be, I did look at that issue when I was troubleshooting. I wasn't sure if it was the same because I'm not trying to use mythic mobs and I'm not using any triggers other than a distance. I also tried moving edited signs by a few blocks (I have seen multiple DXL_edit worlds in my files as well at times)  as suggested in that issue and it didn't make a difference. Doing play and leave repeatedly also didn't fix the issue, but on looking over that thread again I see that someone fixed it by doing play and end repeatedly, so I will try that later today and update here with the results.
