### ISSUE TITLE
Why when I use / dxl I go or when I leave the dungeons do I die?

### ISSUE THREAD

**Issue by koblich1** [DRE2N/DungeonsXL#465]
Hello, I have a doubt in my server download the DungeonsXL and when entering the / dxl edit mode and then when leaving with / dxl leave I appear where I was previously but dead? it's a bug, is the plugin like that?

I await an answer :)

(Sorry English but I had to use Google translator)

**Comment by Sataniel98** [comment]
You are killed to prevent bugs when the saved player data is erroneous. Which version of the server software and DungeonsXL are you running?

**Comment by koblich1** [comment]
My minecraft version is 1.8.8 and Dungeons is 1.16.3 the latest.

How do I solve the data player?

Thanks for you answer <3

**Comment by Sataniel98** [comment]
Due to my vacation, it'll take a week or two until I have the time to reproduce this and find a solution, so I'm sorry but I need to ask you to have some patience.

Further information that might be helpful are:
* Your inventory contents
* Your status effects
* Is there any difference between using /dxl play and /dxl edit? Does setting keepInventoryOnEnter, keepInventoryOnEscape and keepInventoryOnFinish to true make any difference when using /dxl play?

**Comment by koblich1** [comment]
Well, when applying the commands / dxl play, / dxl edit or enter with the poster
the inventory is erased, the effects equal. I have not configured that yet, since it is not with multiple floors. Now if you set that up for 1 floor too, I do not know how to do it: /


Thank you very much for your answers Sataniel, enjoy your holidays :)

**Comment by koblich1** [comment]
I forgot to add that the way I enter the dungeon the items are erased and I go out through / dxl leave or use the poster [End] I appear dead, accompanied by a message that says die or that I have been killed by the boss of the silver form (although he has already defeated him)

**Comment by Sataniel98** [comment]
Thank you for your replies.

"Well, when applying the commands / dxl play, / dxl edit or enter with the poster
the inventory is erased, the effects equal. I have not configured that yet, since it is not with multiple floors." 
That is the default, correct behavior. With just one floor, you can change this in the floor comfiguration (plugins/DungeonsXL/maps/{Floor Name}/config.yml. This file is optional and might not exist yet - just create it in this case. It is however interesting to know which items and status effects you had before joining, because this is what is saved and later restored, which doesn't seem to work herr. Could you please show me the contents of a plugins/DungeonsXL/players/{Player UUID}.yml file while they are in a dungeon?

"accompanied by a message that says die or that I have been killed by the boss of the silver form (although he has already defeated him)"
I believe this is just the normal die message of Minecraft. If a player dies for an unknown reason shortly after taking damage from an NPC, the death message might refer to this NPC.

"Thank you very much for your answers Sataniel, enjoy your holidays :)"
Thank you very much :)

**Comment by koblich1** [comment]
I'm sorry, it's that the effects remain, if not that they also erase the translator I failed: c

**Comment by Sataniel98** [comment]
Do you see errors in the console?

**Comment by koblich1** [comment]
No

**Comment by Sataniel98** [comment]
Fixed, thank you for the report!
