### ISSUE TITLE
Some bugs after migration to 1.13.2

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#497]
Hi,

Recently, (last monday), we have upgrad our server to 1.13.2 with last spigot build tools and DXL 17.3. 

But many things doesn't work as expected :s 

**Can't join a group with signs**
First of all, i've try to put group sign. The signs are correctly converted in DXL BUT, i can't click on it to join a group. Nothing appears when i hit them. I can just break them with /dxl break. There is no lock on it (with LWC for example). I haven't try for the moment if Worldguard 7 could have conflicts with this. 

**Dungeon Signs aren't converted correctly**

I've try to use /dxl play. Everything start fine (Lobby and start sign) but sign give error in console about a wrong block. I've a clue about this but not sure : The IDs of blocks have change in 1.13.2 so i suppose that old IDs don't work anymore? Before start long work on it, i hope you could confirm it o/ 

I haven't try more for the moment, i will give you more feedback as soon as possible.

Thanks o/

**Comment by Tiplish** [comment]
I confirm that BLOCK signs are in trouble (Even if i try with ID or block name). And i've the same bug as #495

**Comment by Sataniel98** [comment]
Thank you for the reports, I'll work on it this weekend :) As for the long loading times, this may be because the dungeons are converted to 1.13 times each time they are instantiated. Try making a backup, loading each world once through /dxl edit and saving it. Larger worlds might need some flying around to convert all chunks. I'm unfortunately not planning to add an automatic way to convert all dungeons as I'll drop older versions anyway at some point. However in 1.13, worlds might take _a bit_ more time to load in general.

BTW, Minecraft doesn't support numeric block IDs and DVs, but Spigot still has a compatibility wrapper that should make it possible to use them to some extend. [I have already worked on a solution that uses the new block data](https://github.com/DRE2N/DungeonsXL/commit/8348c9186793981f4e6ab92fbcde486cc1c7e606), but I'm still not entirely contented with it because the strings are just too long for signs. I might need to come up with my own, shorter format, or think of something better.

**Comment by Tiplish** [comment]
Hi, Any news about the two bugs? Block sign & Ready sign? 

I know that you have few time  (BTW, in end december, lot of people are busy o/), i just would have an estimation if you could try to solve this two major bugs in december or if i have to find another way to occupy people (yeah, 1.13.2 is not enough for them x) ).

Thanks o/

**Comment by Sataniel98** [comment]
It shouldn't take that long. As I said, I have already looked over it last weekend and I think I know what's going on.

**Comment by Sataniel98** [comment]
Fixed in 0.17.4 :)
