### ISSUE TITLE
Set Game Goal

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#518]
Hey Sataniel!

I am Creating my custom floor configs right now, and i wonder if there is any way to set the GameGoal in the config?

I found nothing in here: https://github.com/DRE2N/DungeonsXL/blob/master/src/main/java/de/erethon/dungeonsxl/game/GameRuleProvider.java#L109

and sadly the [Ready]-Sign game type overrides the floor config values, so i can't make my own config with my own game goal.

Is there any way i can do this? If not, can you implement this? Would be really helpful.

And another Question: If i got 2 teams (PvP), how can i give the winner-group the reward when they reach the defined game goal? Like Last-Man-Standing or Similar.

**Comment by Sataniel98** [comment]
Game goals are connected to the game types and not set through configurations. PVP game types disable rewards, because we made the experience that this doesn't work well - players started to fake PVP games with multiple accounts per person just to gain the rewards, and stuff like that.

I understand that the lack of customizability may be dissatisfying, and I have some rough ideas to improve this feature alongside other parts of DXL, but it is unfortunately possible that I won't have time for groundbreaking rewrites until August. I can't forsee my workload in the next semester yet. Still, if you have specific ideas on how to implement improvements, I'm interested in hearing them.

**Comment by BlacksWing** [comment]
I want to swear. I've put up with it. delete

**Comment by Sataniel98** [comment]
@BlacksWing Excuse me...?
