### ISSUE TITLE
Error Occured with spigot

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#523]
Hello,

I'm using DungeonXL since 1weeks and with no change, I have this error now : 
[ScreenShot Error Occured](https://ibb.co/0Dc26JM)
But with no reason... 

Ps: sorry for my english i'm french

**Comment by Sataniel98** [comment]
Hello and thank you for the report. The issue lies in your "externalMobProviders" section of the main configuration. Try removing it and setting the configVersion to any lower version. DXL will regenerate the section upon the next start. This is however definitely bad error handling on my side - I'll look over it and publish a fix as soon as my exams are over.

Regards
Sataniel

PS: If you're more comfortable with it, writing in French is fine. I might stick to English when I'm in a hurry, but I have no problems reading it.
