### ISSUE TITLE
MythicsMobs whith DungeonXL

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#524]
Hello, 

I'm using MythicMobs but when i add mob in dungeon with this command :
/mm mobs spawn [mob] 
he is appear ( good ), I save (/dxl save), but when i play this dungeon (/dxl play [DJ] or /dxl test when i'm in , i see the mob just 1 sec and he is disappear.

I don't know what the problem is.

Ps: sorry again for my english i'm french

**Comment by Sataniel98** [comment]
Please report issues with mobs randomly despawning to the respective mob provider plugin. Instances are technically normal worlds that aren't handled differently than other worlds. In your case, DungeonsXL touchs the mobs even less because it recognizes only mobs spawned through mob signs: https://github.com/DRE2N/DungeonsXL/wiki/signs#mob
