### ISSUE TITLE
Floor config issue

### ISSUE THREAD

**Issue by korthas** [DRE2N/DungeonsXL#556]
**Description**

I can not ban objects, I tried to ban water bucket because they are problematic and can be put on the ground but without success

The fact of not being able to prohibit object and very problematic because the players can also pose boats in front of the mobs so that they go up automatically in the boat and find themselves immobilized permanently (Yes because in minecraft base the mobs go up by default in the object on their way)

And that makes the mobs useless...

**Screenshots / GIFs / videos**

Here is my configuration (Way : \DungeonsXL\maps\mapname\config.yml )

```
forcedGameType: DEFAULT
timeUntilKickOfflinePlayer: 600
timeToNextPlayAfterFinish: 24
fly: false
playerVersusPlayer: true
friendlyFire: false
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
keepInventoryOnDeath: false
initialLives: 1
forbiddenItems:
 - WATER_BUCKET
breakBlocks: false
placeBlocks: false
secureObjects:
 - WATER_BUCKET
```

**Comment by Sataniel98** [comment]
secureObjects prevents items from being removed from the game, like through destruction or the player leaving the group (it is then passed to another group member). forbiddenItems only prevents items from being taken into a dungeon, it does not prevent them from being used, and it is a requirement that must be put into its section instead of the root.
