### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by maxlehot1234** [DRE2N/DungeonsXL#56]
Hi,

I have few questions for you:
1- This plugin works with mythicmobs custom mobs?
2- This plugin allow wave or when player kill mobs, they can access another room/arena/dungeon, maybe by using a portal?
3- When players kill the mobs in a dungeon, is it possible to teleport all players into another dungeon to fight another boss?
4- When players reach the latest dungeon, is it possible to teleport all players (inside the dungeon) into the lobby?
5- Is it possible to set a minimum/maximum player to start a dungeon?
6- Is it possible to have multiple dungeon? Example a very easy dungeon with 2 dungeons in it, a medium with 5 dungeon and a boss and an expert dungeon with 10 dungeon and 1 boss after each 5 dungeon?
7- What's about this page: https://github.com/DRE2N/DungeonsXL/wiki/getting-started
Not a lot of informations in it :p :P A video will be better than text I think ;)

I think it is good for the moment, I know it is a lot, but if you can help me with this, it can be amazing, so I can start working with dungeonxl for a future version of my server ;)

Thank you so much and have a nice day/night ;)

**Comment by Sataniel98** [comment]
Hi,
- 1: Yes, you just have to use MythicMobs signs instead of Mob signs.
- 2 / 3: Setup a multi floor dungeon. Use a floor sign with a mob trigger at the end.
- 4: Dungeons use one lobby, the one of the startFloor. If one floor is finished, the player gets teleported to the start location of the next one.
- 5: Yes, with group signs.
- 6: You can create as many dungeons as you want. You seem to mix up "dungeon" and "floor", though. One dungeon can link together as many floors as you want with the dungeon config.
- 7: Aware. There's currently a lot to do concerning the code itself. I'll work on the documentation when I have a new stable build.

I hope this could help a bit :) Best regards

**Comment by maxlehot1234** [comment]
Thanks for your reply, but for signs: https://github.com/DRE2N/DungeonsXL/wiki/signs

Some images are missing :P

Where I need to put signs? To prevent other players to see them?

I think it will better to set a spawnpoint by a command instead of signs :P

Maybe create commands to leavec a group will be nice too ;)

**Comment by Sataniel98** [comment]
The command to leave a group is /dxl leave. Signs will be removed when the dungeon map gets instantiated. Well, the authors decided to use signs and not commands, probably to make it visible.
