### ISSUE TITLE
Door trigger issue

### ISSUE THREAD

**Issue by Kvosty** [DRE2N/DungeonsXL#593]
Hi, me, again

Maybe i dont understand how to use it, or maybe its just dont work..

I have sign on Door with text

[Door]

U Krompacik

but when i right clik on Door with item named "Krompacik" nothing happen.. How to fix that? My server version is paper 1.14.2

**Comment by Sataniel98** [comment]
It does work.

![ezgif-1-5ae0f37e0fee](https://user-images.githubusercontent.com/8921300/59632159-dd1fce00-9149-11e9-94ad-febac86b03c2.gif)

The problem might be that the item only activates if you click somewhere in the air, but not if you click a block. This is because the use item trigger is designed to work with multiple signs triggered by one item and with things that aren't clickable (like for example, click with the item in your hand and some mobs spawn). But I see that this is very counter-intuitive, I'll change this to work with clicking blocks.

**Comment by Kvosty** [comment]
Thanks for your time!

Now i understand how it works. I really appreciate your access to the players who use your plugins. It doesn't seem so often.

If you will ever need help with testing, you can count on me

**Comment by Sataniel98** [comment]
Thanks, please let me know if you encounter any other problems.

**Comment by Kvosty** [comment]
Should i create a new topic for any problem each? or I can write them here? I know at least two more bugs, but i think they are related only with 1.14.2 version.

**Comment by Sataniel98** [comment]
Please create new issues for each issue because I use them as a to do list and close them once they are resolved.

**Comment by Sataniel98** [comment]
lol, it turned out it was actually supposed to work like you tried to use it but didn't because of a bug.
