### ISSUE TITLE
End Sign only works for me, not players

### ISSUE THREAD

**Issue by fenix12585** [DRE2N/DungeonsXL#602]
**Description**

[//]: # End sign only works for me not other players. Nothing shows in the console and players do not get an error message. When I use the sign it works fine. I did find some older bugs involving this situation, but they were either scheduled to be fixed in a previous version or were different because they provided console output.

**Reproduce**

[//]: # Build dungeon test end sign with multiple accounts or contact me so I can give you access to dungeon and run a playthough on play.hydra.army

**Expected behavior**

[//]: # nothing. 

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
none... single dungeon
```

dxl 0.18 snap 767     spigot 1.13.2

**Comment by Sataniel98** [comment]
Does the end sign work if it is triggered differently, for example with a distance trigger? Is if it works related to if you are OP?

**Comment by fenix12585** [comment]
Hello,

Thank you for your quick response. What do you mean with a distance
trigger?

Also, I have removed OP from myself testing if I was missing a permission
node on my players but I was still able to use the sign.

**Comment by Sataniel98** [comment]
Every sign in DungeonsXL (except passive signs like for example the lobby sign that just marks a location) is triggered through a trigger specified in the last line. For example,
[Mob]
ZOMBIE
0,1
D5
spawns a zombie if a player is within a range of 5 blocks to the position of the sign. Specifying no trigger at all usually triggers the sign immediately when it is initialized, but if this makes no sense, an interaction trigger is generated automatically instead. This is the case among others for end signs, so an end sign with nothing but [End] in the first line won't be triggered before all players click the interaction trigger that is generated where the sign was. Of course, you can still override this trigger, like:
[End]
/empty
/empty
D5
If the end sign can still be triggered through e.g. a distance, redstone or mob trigger, this is a hint that the action of clicking the sign itself is for some reason not recognized; if not, the mechanic of the end sign itself is probably erroneous. The latter is probably way harder to resolve because there are few clues why it wouldn't work for others when it works perfectly fine for you, but sign interactions taken by themselves could be hindered by about anything and are possibly not even bugs, like interfering protection plugins or the Vanilla spawn protection set in the server.properties.
