### ISSUE TITLE
MAJOR ERRORS

### ISSUE THREAD

**Issue by maegae** [DRE2N/DungeonsXL#676]
The server keeps crashing due to dungeons. From what I can read and understand of the error logs, it seems to be waiting on chunks to load in the DXL_Game_# instances. The crashes are never consistent, it can be after someone plays 20 games in a row or it can be someone's first game after the server restarts. I am seriously at my wits end of what to do, I've spent loads of time on these dungeons and I really don't want to get rid of them but I may have to due to how unstable it is. 

This is the full crash log. The server is using 1.14.4 Purpur, I remember hearing that it was unstable in 1.14, if you know of this issue will it be fixed by reverting to 1.13?
https://pastebin.com/RG4antpD

These are the plugins the server has:
AdvancedPortals, AreaShop, AuctionHouse, BossShopPro, ChestShop, ColoredAnvils\*, CoreProtect, CustomCrafting, CustomHeads\*, DiscordSRV, DiscordSRV-Staff-Chat\*, DungeonsXL, EmojiChat, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, F3NPerm, GriefPrevention, Harbor, Hat, InventoryRollback, LastLoginAPI, LibsDisguises, LimitPillagers, LuckPerms, MineableSpawners, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MythicArtifacts, MythicMobs, OldCombatMechanics, OpenInv\*, Parties, PetMaster, PixelPrinter, PlaceholderAPI, PlayerParticles, PlayerRider, PluginConstructorAPI, ProtocolLib, RandomTeleport, RFChairs, SuperTrailsPro\*, SuperVanish, TradeSystem, TreeGravity, TrollBoss, UberEnchant, Vault, Vivecraft-Spigot-Extensions\*, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, xRay\*

I'd really appreciate some help

**Comment by Sataniel98** [comment]
It looks like the server crashs when a chunk is loaded because DungeonsXL requests to interact with a mob sign whose position in the actual world isn't loaded yet. If it works or not in 1.13 depends on if it is a chunk error or a bug in the server software. It is very possible that this is caused by Paper's modifications. What you can do is

1) check if the crashs only occur in a certain dungeon world - in this case, it should be possible to fix it with a tool like MCEdit.

2) if this doesn't help, try using Spigot if possible. Spigot doesn't use Paper's asynchronous chunk loading and should be less error prone. If it works with Spigot, report the issue to Paper.

If this still doesn't help, please get back to me.

**Comment by maegae** [comment]
How would i fix this using MCEdit?

**Comment by Sataniel98** [comment]
As far as I know, it has a tool to fix erroneous chunks.
