### ISSUE TITLE
Dungeons crash upon entering other world right after create (?) or delete dungeon world

### ISSUE THREAD

**Issue by DriesMelkebeke** [DRE2N/DungeonsXL#823]
Server crashes right after someone entered the nether and at the same time a dungeon world got deleted (or created, not sure). Can not replicate the issue.

Using Paper 1.15.2 (Tuinity version 7c03cbe)
Dxl version: V0.18-Snapshot-968

Crash report provided below.
[crash-2020-06-16_21.44.38-server.txt](https://github.com/DRE2N/DungeonsXL/files/4789170/crash-2020-06-16_21.44.38-server.txt)

https://pastebin.com/d5gLMyqg

**Comment by Sataniel98** [comment]
I'm sorry for the late reply.

The server crashs because "No chunk holder after ticket has been added". This is something server-internal - I don't see this being related to any plugin. If at all, there's a Bukkit feature called plugin tickets to handle when a chunk unloads, but DXL doesn't use it anywhere. If it still occurs with 1.16.4, it might be worth reporting it to Paper / Spigot.
