### ISSUE TITLE
pixelmon compatible + other question

### ISSUE THREAD

**Issue by erposse90** [DRE2N/DungeonsXL#959]
hello, I would like to know how I can place crates that give pixelmon items and if it was possible to enable the natural spawn of mobs / animals in the created dimensions (so as to spawn pixelmon)
finally is there a way to give a max time to the players who enter the dungeon? obviously after the time they should be thrown out

**Comment by Sataniel98** [comment]
Server softwares based on Forge mappings are not supported. They might work to some extend, but I can't guarantee anything.

Natural spawning is by design not possible. You can use [mob signs](https://github.com/DRE2N/DungeonsXL/wiki/dungeon-npcs) to summon mobs.

Dungeons with gameGoal set to TIME_IS_RUNNING or TIME_SCORE can use the timeToFinish game rule.

https://github.com/DRE2N/DungeonsXL/wiki/game-rules

https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

**Comment by erposse90** [comment]
tnks very much, for put in lootchest pixelmon items/custom items? mob sign worck to spawn pixelmon mob?? if true,how?

**Comment by Sataniel98** [comment]
If Pixelmon has a command to summon mobs, you can register it as explained here: https://github.com/DRE2N/DungeonsXL/wiki/dungeon-npcs

Loot chests should work as they are.

**Comment by erposse90** [comment]
unfortunately I had to delete the plugin because during an event the players were teleported in a dimension never created by me, instead of the one created, blocking them and preventing any use of commands, in addition to teleport them with console command did not work, as well as not  the kill or the dxl leave command worked .. surely, however, it is an error given by the compatibility with magma
