### ISSUE TITLE
Floor Config file

### ISSUE THREAD

**Issue by Sh4d0wR1ft** [DRE2N/DungeonsXL#96]
Hello there!
I have just started using this this plugin and it is great.
Just one thing though, I want to let players use their own items in a dungeon but cannot find the config file in the maps folder. 

Please help!

**Comment by Sataniel98** [comment]
You have to create the file yourself because the floor configuration is optional. Note that the game rules you define in the floor configuration can also be fetched from other sources: If you create a multi floor dungeon with multiple maps, you probably want to have the same config values for all maps. In such a case, it's easier to use the dungeon configuration and to add the values to the defaultValues or to the overrideValues section. Even without a multi floor setup, the default values or the values from the main config or the game type are sometimes sufficient for small projects. Therefore, there's just a file if it is needed either because you've created it or to store the players that are allowed to edit the map without the permission node.
