### ISSUE TITLE
How i can use API with signs?

### ISSUE THREAD

**Issue by 1bye** [DRE2N/DungeonsXL#968]
Hi. I want remove sign "[end]" and place block. When you stand in this block you finish dungeon. This my code but dont work:
_(in this moment code dont finish dungeon. At this moment code replace sign to block!)_
**dnXLManager.java**

`
public class dnXLManager implements Listener {

    private Main plugin;

    public dnXLManager(Main plugin) {
        this.plugin = plugin;
    }
	
	public void dnXL() {
		GameWorld getGameWorld;
		
		InstanceWorld world = game;
		String end = "[end]";
		
		String line = world.getDungeonSign(null).getLine(0);
		
		if(line == end) {
			Location loc = world.getDungeonSign(null).getSign().getLocation();
			world.getWorld().getBlockAt(loc).setType(Material.AIR);
			double y = loc.getY();
			y = y - 1;
			loc.setY(y);
			world.getWorld().getBlockAt(loc).setType(Material.GOLD_BLOCK);
		}
	}
	
}
`

**Main.java**

public class Main extends JavaPlugin{

	DungeonsAPI dxl;
	Logger log = Logger.getLogger("Minecraft");
	//enable
	@Override
    public void onEnable() {
    	//DXL API
    	if (!Bukkit.getPluginManager().isPluginEnabled("DungeonsXL")) return;
    	dxl = (DungeonsAPI) Bukkit.getPluginManager().getPlugin("DungeonsXL");
    	//enable string
    	getLogger().info("Dungeons enable!");
    	//DXL Manager
    	Bukkit.getPluginManager().registerEvents(new dnXLManager(this),this);
    } 
    //disable
    public void onDisable(){
    	getLogger().info("Dungeons disable!");
    }
    

}`
**Thanks for watching this issue. I hoping you help me!**
_(Good Plugin and Good Job!)_

**Comment by Sataniel98** [comment]
Hi,
there's a lot wrong here, so I'll try to go through it step by step.
```
Logger log = Logger.getLogger("Minecraft");
```
It doesn't look like you're using this logger, and getting the logger by name is considered bad practice since it's implementation specific. You can just use the Plugin#getLogger() function like you already do.

```
dnXLManager
```
It's a convention that class names should begin with an uppercase letter.

```
public void dnXL() {
```

Listener methods must be annotated with @EventHandler and use an event. Also, you should use expressive method names, like:
```
@EventHandler
public void onGameWorldStartGame(GameWorldStartGameEvent event) {
```

You can iterate over the dungeon signs in the game world in order to find the end sign:
```
for (DungeonSign sign : event.getGameWorld().getDungeonSigns()) {
    if (sign == null || !sign.getName().equals("End")) {
        continue;
    }
    // Your code - if the code here is reached, "sign" is an end sign
}
```

I didn't test it though. Not sure if the event fires before or after the end sign is initialized. This could cause problems. A cleaner solution would be to reimplement the [end sign](https://github.com/DRE2N/DungeonsXL/blob/master/core/src/main/java/de/erethon/dungeonsxl/sign/button/EndSign.java) the way you need it or to implement a new trigger that fires when a player steps on a block. There is however no trigger API yet, so you'd have to work with the internals of DXL (which isn't supported).

**Comment by 1bye** [comment]
Thanks. But i do this code and anything dont work. I do Dungeon Name "Tier1" and write /dxl play Tier1. Click to Ready and sign dont remove! `
public class dnXLManager implements Listener {

    private Main plugin;

    public dnXLManager(Main plugin) {
        this.plugin = plugin;
    }
	
    @EventHandler
    public void onGameWorldStartGame(GameWorldStartGameEvent event) {
    	for (DungeonSign sign : event.getGameWorld().getDungeonSigns()) {
    	    if (sign == null || !sign.getName().equals("End")) {
    	        continue;
    	    }
    	    // Your code - if the code here is reached, "sign" is an end sign
    	    Location loc = sign.getSign().getLocation();
    	    System.out.println(loc);
    	    sign.getSign().setType(Material.AIR);
    	}
    }
	`

**Comment by Sataniel98** [comment]
You're calling that on the BlockState. It won't change the world unless you update it.

**Comment by 1bye** [comment]
How i can uptade the world?

**Comment by Sataniel98** [comment]
You don't update the world but the BlockState, and in this case you shouldn't use the state at all but its Block object.

JavaDocs for Bukkit are available here: https://hub.spigotmc.org/javadocs/spigot/
