### ISSUE TITLE
World Name Template

### ISSUE THREAD

**Issue by MonzterDev** [DRE2N/DungeonsXL#985]
**Please describe the use case or the problem your request is related to.**
I'd like to make a Skript so I can control things which will only happen in the Dungeon. I could do something like `if player is in world containing "DUNGEON_CASTLE"`

(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...];)

**Describe the solution you'd like**
Allow us to configure how Dungeon Worlds will generate their names with a Pre-Fix of sorts. Currently Dungeons generate like "DXL_GAME_X" but if we could config, based on each Dungeon something like "DXL_{PREFIX}_GAME_X"
(A clear and concise description of what you want to happen.)

**Describe alternatives you've considered**
I've also thought about having a WorldGuard generate upon the world generation of the Dungeon as well. I feel like this might actually be semi-easily possible considering cords don't change when a Dungeon world is generated.

It'd just be great if there was an easy way for other scripting Plugins to be able to differentiate if a Player is in a specific Dungeon.
(A clear and concise description of any alternative solutions or features you've considered.)

**Comment by Sataniel98** [comment]
Checking which dungeon an instance world belongs to is easily possible through the API. The methods to do so are [DungeonsAPI#getGameWorld(World)](https://erethon.de/javadocs/dungeonsxl/de/erethon/dungeonsxl/api/DungeonsAPI.html#getGameWorld(org.bukkit.World)) and [GameWorld#getDungeon()](https://erethon.de/javadocs/dungeonsxl/de/erethon/dungeonsxl/api/world/GameWorld.html#getDungeon()).

Static names aren't possible since they defeat the purpose of this plugin, which is to allow instantiation of the same world multiple times simultaneously. Prefixes wouldn't help much since few to no plugins allow regex expressions for world names. That leaves Skript as the only plugin that might benefit from a feature like that, and I don't have any plans to support Skript or work on DXL with it in mind.

I'm sorry but I decided against this suggestion.
