### ISSUE TITLE
Basalt_delta biome causes extreme TPS issues when running on Purpur.

### ISSUE THREAD

**Issue by JackWalms** [DRE2N/DungeonsXL#987]
Whenever a DXL instance is loaded with the biome "basalt_delta" - May possibly be other nether biomes I just haven't checked yet - The TPS drops to below 1. This doesn't happen on Spigot, Paper or Tuinity and according to the Purpur devs, its not them causing this issue.

Here is a spark report of the event happening -> https://spark.lucko.me/#0jWw4akpGf

I really have no other insight to offer; But Malfrador did reproduced the issue and said that the JavaX script engine is taking an extremely long time validating the mob spawning of slimes.

**Comment by Malfrador** [comment]
To add to this, it does _not_ happen when loading the same world as a normal world (e.g. with Multiverse) and its also not related to WorldEdit. It also does not happen with another plugin blocking the spawning of mobs in that world (e.g. WorldGuard).
Another spark report, just for fun: https://spark.lucko.me/#0VINE9zyw8

**Comment by Sataniel98** [comment]
Did they say anything other than it's not their fault?

**Comment by JackWalms** [comment]
They didn't even give the issue the time of day. The moderator pinged the dev but as soon as he saw it stemmed from another plugin he didn't bother checking the timing reports.

This is basically all they said -> https://gyazo.com/ce24f52aba1aac806eaec1cc71e37c56

**Comment by Sataniel98** [comment]
Well. That's clearly just wrong. Biomes in Minecraft do much more than just being there, a lot of other features that don't inherently have anything to do with biomes are only or at least much more often used in certain biomes. You don't need to "mess with biomes" in order to have issues that only appear in certain biomes.

DungeonsXL doesn't touch biomes or slimes anywhere either, but that dosen't mean it's not DXL's fault. I can't rule out DXL does something wrong that might not cause issues in Spigot or Paper because of some implementation detail that prevents it or makes it unnoticeable, while Purpur does it somehow differently and we can see the error in its full glory.

Anyway, realistically speaking, I'll probably not be able to work on it, at least not in a reasonable timeframe. There are already too many issues piling up that occur with all mainstream server softwares, but I'm too short on time to fix them. I'm very sorry for that. We can still leave the issue open in case new information are found or another dev has clue.

**Comment by JackWalms** [comment]
The Purpur dev sent this in the discord. 

> BillyGalbreathToday at 3:07 AM
> Purpur ships with the Rhino JS engine. i've seen one instance where this caused an issue with a plugin, but the fix was to tell the plugin to use the Nashorn engine. https://github.com/pl3xgaming/Purpur/issues/148
> (cc @Malfrador)
> 
> the problem is plugins like to just use whatever engine is available in the JVM and assume only Nashorn is present. Nashorn was added to the JVM in Java 8, but was marked for removal in Java 11 for a future release yet to be determined (https://openjdk.java.net/jeps/372), so I stopped using Nashorn for Purpur's internal things (like the customizable player exp equations, etc) and ship with the older (but rock solid) Rhino engine
> funny part is they added Nashorn to replace Rhino, but ended up not wanting to maintain Nashorn so now are dropping it lol. So, a lot of devs are going back to Rhino, which was maintained the entire time and has no plans to stop maintaining it in the future.

**Comment by Sataniel98** [comment]
DungeonsXL doesn't use JavaScript so it doesn't use either of them.

**Comment by Malfrador** [comment]
Should be fixed by https://github.com/pl3xgaming/Purpur/commit/0d25d391e3e620faa070e91069ce8a935ee87940
